# Generated by Django 5.1.3 on 2024-11-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.item')),
                ('burn_time', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SC', 'Scented'), ('PI', 'Pillar'), ('DE', 'Decrotive'), ('TW', 'Twisted'), ('TA', 'Tapper')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candles/')),
            ],
            bases=('core_app.item',),
        ),
    ]
