# Generated by Django 5.1.3 on 2024-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='category',
            field=models.CharField(choices=[('SC', 'Scented'), ('PI', 'Pillar'), ('DE', 'Decorotive'), ('TW', 'Twisted'), ('TA', 'Taper')], max_length=2),
        ),
    ]
