# Generated by Django 5.1.3 on 2024-11-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_userprofileinfo_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
