# Generated by Django 5.1.3 on 2024-12-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_order_orderitem_order_list_of_items'),
        ('core_app', '0003_alter_candle_category'),
    ]

    operations = [
    ]
