# Generated by Django 5.1.3 on 2024-12-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_merge_20241203_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='list_of_Items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
