# Generated by Django 5.1.3 on 2024-11-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
